name: ycng228
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.2.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py39ha30fb19_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - appnope=0.1.2=py39hecd8cb5_1001
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py39h63b48b0_1004
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.4.26=hecd8cb5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.6.15=py39hecd8cb5_0
  - cffi=1.15.1=py39hc55c11b_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py39h6e9494a_0
  - cryptography=37.0.4=py39h9c2a9ce_0
  - debugpy=1.5.1=py39he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - flatbuffers=2.0.7=hf0c8a7f_0
  - frozenlist=1.3.1=py39h6218fd2_0
  - gast=0.4.0=pyh9f0ad1d_0
  - giflib=5.2.1=hbcb3906_2
  - google-auth=2.11.1=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.47.1=h834a566_6
  - grpcio=1.47.1=py39h69d5c6f_6
  - h5py=3.7.0=nompi_py39hf4bc8c9_101
  - hdf5=1.12.2=nompi_hc782337_100
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39h6e9494a_0
  - ipykernel=6.9.1=py39hecd8cb5_0
  - ipython=8.3.0=py39hecd8cb5_0
  - jedi=0.18.1=py39hecd8cb5_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=hac89ed1_2
  - jupyter_client=7.2.2=py39hecd8cb5_0
  - jupyter_core=4.10.0=py39hecd8cb5_0
  - keras=2.10.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - krb5=1.19.3=hb49756b_0
  - libabseil=20220623.0=cxx17_h844d122_4
  - libblas=3.9.0=16_osx64_openblas
  - libcblas=3.9.0=16_osx64_openblas
  - libcurl=7.83.1=h372c54d_0
  - libcxx=14.0.6=h9765a3e_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=10_4_0_h97931a8_25
  - libgfortran5=11.3.0=h082f757_25
  - liblapack=3.9.0=16_osx64_openblas
  - libnghttp2=1.47.0=h7cbc4dc_1
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libpng=1.6.38=ha978bb4_0
  - libprotobuf=3.21.6=hbc0c0cd_1
  - libsodium=1.0.18=h1de35cc_0
  - libsqlite=3.39.3=ha978bb4_0
  - libssh2=1.10.0=h7535e13_3
  - libzlib=1.2.12=hfd90126_3
  - llvm-openmp=14.0.4=ha654fa7_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h63b48b0_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - multidict=6.0.2=py39h63b48b0_1
  - ncurses=6.3=hca72f7f_3
  - nest-asyncio=1.5.5=py39hecd8cb5_0
  - numpy=1.23.3=py39h34843a6_0
  - oauthlib=3.2.1=pyhd8ed1ab_0
  - openssl=1.1.1q=hca72f7f_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.1.2=py39hecd8cb5_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=4.21.6=py39h7a8716b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.5.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.13=hdfd78df_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=22.3.0=py39he9d5cce_2
  - re2=2022.06.01=hb486fe8_0
  - readline=8.1.2=hca72f7f_1
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py39hae1ba45_1
  - scipy=1.9.1=py39h9488793_0
  - setuptools=63.4.1=py39hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h6e38e02_1
  - sqlite=3.39.2=h707629a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py39h1644bb1_2
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=cpu_py39hb0a6171_0
  - tensorflow-base=2.10.0=cpu_py39h4341d28_0
  - tensorflow-estimator=2.10.0=cpu_py39h4d6c197_0
  - termcolor=2.0.1=pyhd8ed1ab_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h5d9f67b_0
  - tornado=6.1=py39h9ed2024_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022c=h04d1e81_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39h701faf5_0
  - xz=5.2.5=hca72f7f_1
  - yarl=1.7.2=py39h63b48b0_2
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h4dc903c_3
  - pip:
    - appdirs==1.4.4
    - beautifulsoup4==4.11.1
    - bs4==0.0.1
    - cssselect==1.1.0
    - fake-useragent==0.1.11
    - feedparser==6.0.10
    - lxml==4.9.1
    - pandas==1.5.0
    - parse==1.19.0
    - pyee==8.2.2
    - pyppeteer==1.0.2
    - pyquery==1.4.3
    - pytz==2022.4
    - requests-html==0.10.0
    - sgmllib3k==1.0.0
    - soupsieve==2.3.2.post1
    - tqdm==4.64.1
    - w3lib==2.0.1
    - websockets==10.3
    - yahoo-fin==0.8.9.1
